# Site settings
title: 一派胡言
url: “"https://zhangyet.github.io"
baseurl: ""
#timezone: Asia/Chongqing
description: >
   dantezy 的在线栋笃笑	     

# Your information
email: zhangyet@gmail.com
author: dantezy
avatar: "https://www.gravatar.com/avatar/9d4a72055a6ab800d99f11d0822f0d2c"
profile: 深圳后端码农
twitter_username: dantezy2814
#github_username: ZhangYet
profile_links:
  Email: "zhangyet@gmail.com"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
