# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Inferno's Song
tagline:          'python, emacs'
url:              http://zhangyet.github.io/

author:
  name:           'Dante Zhang'
  url:            http://zhangyet.github.io/

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:		  https://github.com/ZhangYet/zhangyet.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
